language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
before_script:
  - |
    (travis_wait cargo install rustfmt --force || true)
script:
  - |
    export PATH="$PATH":~/.cargo/bin &&
    export RUST_BACKTRACE=1 &&
    echo "\$ rustfmt --version" &&
    cargo fmt -- --version &&
    cargo fmt -- --verbose --write-mode=diff &&
    (test "$TRAVIS_RUST_VERSION" == nightly || cargo build --verbose) &&
    (test "$TRAVIS_RUST_VERSION" != nightly || cargo build --verbose --features "dev") &&
    RUST_BACKTRACE=1 cargo test --verbose &&
    cargo doc --no-deps
matrix:
  allow_failures:
    - rust: nightly
notifications:
  email:
    on_success: never
