[package]
name = "emerald-rs"
version = "0.25.6"
authors = ["Dmitry Ulanov <dulanov@gmail.com>", "Constantine Kryvomaz <kostiyantynk@gmail.com>", "Stewart Mackenzie <setori88@gmail.com>", "Wei Tang <hi@that.world>"]
description = "Ethereum secure account management core libary"
homepage = "https://etcdevteam.com"
repository = "https://github.com/ETCDEVTeam/emerald-rs"
documentation = "https://docs.rs/emerald-core"
keywords = ["ethereum", "ethereum-classic", "blockchain", "ffi", "crypto-wallet", "cold-storage"]
categories = ["embedded", "external-ffi-bindings"]
readme = "README.md"
license = "Apache-2.0"

[badges]
travis-ci = { repository = "ETCDEVTeam/emerald-rs" }
appveyor = { repository = "ETCDEVTeam/emerald-rs" }

[lib]
name = "emerald_rs"
path = "src/lib.rs"
#crate-type = ["rlib", "cdylib"]

[dependencies]
time = "0.1"
futures = "0.1"
jsonrpc-core = "8.0"
jsonrpc-http-server = "8.0"
lazy_static = "1.0"
log = "0.4"
regex = "1.0"
hex = "0.3"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
glob = "0.2"
uuid = { version = "0.5", features = ["serde", "v4"] }
secp256k1 = { version = "0.9", features = ["rand"] }
rand = "0.3"
byteorder= "1.2"
ethabi = "2.0.0"
num = "0.2"
bitcoin = "0.13.2"
aes-ctr = "0.1"
sha2 = "0.7"
sha3 = "0.7"
pbkdf2 = "0.2"
scrypt = "0.1"
hmac = "0.6"
# optional dependencies
emerald-rocksdb =  { version = "0.10.3", optional = true }
hyper = { version = "0.12", optional = true }
reqwest = { version = "0.9", optional = true }
clippy = { version = "0.0", optional = true }
chrono = "0.4"
hidapi = "0.4"

[dev-dependencies]
tempdir = "0.3"
quickcheck = "0.6"
# quickcheck_macros = "0.4"

[features]
default = ["http", "emerald-rocksdb"]
http = ["hyper", "reqwest"]
dev = ["clippy"]
fs-storage = []
